### ISSUE TITLE
Run FE Chasedown Analysis

### ISSUE THREAD

**Issue by TM00** [TrimbleSolutionsCorporation/TSDRemotingAPIExamples#4] opened 2022-09-21 08:56 UTC
Hi Trimble team,

Can one run a FE Chasedown analysis from the API? I can get a `AnalysisType.FirstOrderLinear` to work as in the [CreatingAndAnalyzingModel](https://github.com/TrimbleSolutionsCorporation/TSDRemotingAPIExamples/tree/master/CreatingAndAnalyzingModel) example. When I change it to `AnalysisType.FEChaseDown` it seems that the analysis doesn't run.  

Specifically the following line:

`var analysedLoading = await model.RunAnalysisAsync( AnalysisType.FEChaseDown);`

I've also tried it with a separate TSD test model. 

If you require more info or a minimal example, please let me know.

**Comment by MattSTrimble** [comment] 2022-09-30 08:59
Hi Theo

The problem is that FE Chasedown cannot be run on its own. When running analysis within the TSD UI, the FE Chasedown is run as part of Analyze All, because it requires seed nodes from decomposition and results from other analyses. Therefore, it cannot be run individually, and when you try to do this from the API, nothing will happen.

It's not currently possible to run Analyze All from the API. We will add this capability and aim to release it soon.

Kind regards,
Matt

**Comment by TM00** [comment] 2022-09-30 09:51
Hi Matt,

Thanks a lot for the explanation. That makes sense :) 

It would be great if we could run Analyze All from the API, looking forward to that feature!  I presume design features are also planned for a future release, similar to the ones available in the Live-Link with Grasshopper.

I came across the developers forum recently and will ask my future questions there. I presume that is the appropriate forum for questions and feature requests.

Thanks again!

Kind regards
Theo

**Comment by MattSTrimble** [comment] 2023-03-01 13:00
Hi

We have just completed implementation to enable running the "Analyze All" and Design All" commands. This will be released in a future version 23.1.0.

(Note that the next version, due out soon, is 23.0.0. These new features will be enabled in the version after that.)

Thanks,
Matt

**Comment by TM00** [comment] 2023-03-02 08:17
Hi Matt,

That is great news! Thanks for the update!

Kind regards
Theo

**Closed as completed** 2024-03-07 15:02 UTC
